### ISSUE TITLE
New air types [$10]

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/1.13-board#1]
*This issue is part of the 1.13.x compatibility Epic.*

All contributions are subject to the [Glowstone CLA](https://glowstone.net/cla). **In short, contributions must not contain any content (code or otherwise) copied from,
inspired by or based upon content from Mojang or third-party projects that are based on such content (CraftBukkit, Spigot, Forge, ...).**

---

**Description**:

1.13 introduced new technical air types to be used in special scenarios:
- [ ] Void air: for blocks at Y>255 or Y<0, and in unloaded chunks.
- [ ] Cave air: used for when setting empty space in generated structures and caves.

**Reference Documentation**:

* https://minecraft.gamepedia.com/Air

**Relevant Code**:

* https://github.com/GlowstoneMC/Glowstone/blob/1.13/src/main/java/net/glowstone/chunk/ChunkSection.java
* https://github.com/GlowstoneMC/Glowstone/blob/1.13/src/main/java/net/glowstone/generator/GlowChunkData.java
* https://github.com/GlowstoneMC/Glowstone/tree/1.13/src/main/java/net/glowstone/generator/structures
* https://github.com/GlowstoneMC/Glowstone/blob/1.13/src/main/java/net/glowstone/generator/decorators/overworld/SurfaceCaveDecorator.java

**Comment by professorg** [comment]
For a start, should the SurfaceCaveDecorator and GlowDungeon set CAVE_AIR instead of AIR? How far does that get us? I can't seem to find any other underground structures that set air.

Also, is void air actually necessary? The wiki cites that it's only used internally to represent unloaded blocks.

**Comment by mastercoms** [comment]
I think that'll get us covered for cave air. For void air, we just need to return it if a location in an unloaded chunk or invalid location (out of height bounds) is queried for type.
