### ISSUE TITLE
Tag API implementation [$20]

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/1.13-board#11]
*This issue is part of the 1.13.x compatibility Epic.*

All contributions are subject to the [Glowstone CLA](https://glowstone.net/cla). **In short, contributions must not contain any content (code or otherwise) copied from,
inspired by or based upon content from Mojang or third-party projects that are based on such content (CraftBukkit, Spigot, Forge, ...).**

---

**Description**:

We need to implement the object data representation for tags, so that they can be read by the server logic after serialization from data packs.

**Reference Documentation**:

https://papermc.io/javadocs/paper/1.13/org/bukkit/Tag.html
https://wiki.vg/Data_Generators
https://minecraft.gamepedia.com/Tag

**Relevant Code**:

https://github.com/GlowstoneMC/Glowstone/blob/1.13/src/main/java/net/glowstone/data/GlowTag.java

**Related to:**

#2 
#4

**Comment by smartboyathome** [comment]
This has been done by the redstone transformer.
