### ISSUE TITLE
Convert BlockData to numerical IDs [$75]

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/1.13-board#27]
*This issue is part of the 1.13.x compatibility Epic.*

All contributions are subject to the [Glowstone CLA](https://glowstone.net/cla). **In short, contributions must not contain any content (code or otherwise) copied from,
inspired by or based upon content from Mojang or third-party projects that are based on such content (CraftBukkit, Spigot, Forge, ...).**

---

**Description**:

We need a system to parse base block types and properties to generate BlockData into networkable/writeable numerical IDs.

**Reference Documentation**:

https://wiki.vg/Data_Generators

**Relevant Code**:

https://github.com/GlowstoneMC/Glowstone/tree/1.13/src/main/java/net/glowstone/block/data
https://github.com/GlowstoneMC/Glowstone/tree/1.13/src/main/java/net/glowstone/block/flattening

**Related to:**

#3

**Comment by smartboyathome** [comment]
This is done.
