### ISSUE TITLE
Retrieve vanilla data packs [$25]

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/1.13-board#5]
*This issue is part of the 1.13.x compatibility Epic.*

All contributions are subject to the [Glowstone CLA](https://glowstone.net/cla). **In short, contributions must not contain any content (code or otherwise) copied from,
inspired by or based upon content from Mojang or third-party projects that are based on such content (CraftBukkit, Spigot, Forge, ...).**

---

**Description**:

Have a way to automatically get vanilla data packs and reports without redistribution. This will likely involve downloading the Minecraft server automatically and running it for generating data reports. We need to also add a flag to prevent downloading the Minecraft server if people choose to opt out of using Mojang data.

**Reference Documentation**:

https://wiki.vg/Data_Generators

**Related to:**

#4

**Comment by aramperes** [comment]
# Implementation notes

Glowstone would only be interested in server-side **data packs** and **registry reports**. Those can be generated by downloading the Vanilla server JAR, and running:

```
java -cp server.jar net.minecraft.data.Main --reports --server
```

Which produces the directory structure:

```
generated/
├── data
│   └── minecraft
│       ├── advancements
│       │   ├── adventure
│       │   ├── end
│       │   ├── husbandry
│       │   ├── nether
│       │   ├── recipes
│       │   │   ├── brewing
│       │   │   ├── building_blocks
│       │   │   ├── combat
│       │   │   ├── decorations
│       │   │   ├── food
│       │   │   ├── misc
│       │   │   ├── redstone
│       │   │   ├── tools
│       │   │   └── transportation
│       │   └── story
│       ├── recipes
│       └── tags
│           ├── blocks
│           ├── fluids
│           └── items
├── reports
└── tmp

```

## Automating

My thoughts on implementation:
* Glowstone should look into a local directory (`generated` by default?) for the data packs and reports
* If no data is found, Glowstone should fail at startup, giving the following possible solutions:
  * Generating the required files yourself by downloading the Vanilla server from Mojang and running the command
  * Using a command-line flag (`--download-vanilla-data`) or config entry to enable auto-downloading the Vanilla jar and generating the reports

If the second option is used by the end-user, it should be possible to configure which URL to download the JAR from, defaulting to Mojang's servers.

**Comment by smartboyathome** [comment]
Do we actually need to automate this? Now that vanilla's gone through 1.13, 1.14, 1.15, and soon 1.16, and at most this file would change once per version. We could just hand edit it based off the changelogs for each version.

**Comment by mastercoms** [comment]
Yes, because we don't want to redistribute the file.

**Comment by birbe** [comment]
Plus a bounty's a bounty :P

**Comment by smartboyathome** [comment]
This is now being handled by redstone-transformer.
