### ISSUE TITLE
Use data packs for recipes [$30]

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/1.13-board#6]
*This issue is part of the 1.13.x compatibility Epic.*

All contributions are subject to the [Glowstone CLA](https://glowstone.net/cla). **In short, contributions must not contain any content (code or otherwise) copied from,
inspired by or based upon content from Mojang or third-party projects that are based on such content (CraftBukkit, Spigot, Forge, ...).**

---

**Description**:

We currently use a custom system for representing crafting data, but this should be replaced with a data pack based system.

**Reference Documentation**:

https://minecraft.gamepedia.com/Recipe

**Relevant Code**:

https://github.com/GlowstoneMC/Glowstone/blob/1.13/src/main/java/net/glowstone/inventory/crafting/CraftingManager.java
https://github.com/GlowstoneMC/Glowstone/blob/1.13/src/main/resources/builtin/recipes.yml

**Related to:**

#4

**Comment by smartboyathome** [comment]
This has been implemented by the redstone-transformer.
